### ISSUE TITLE
本のコマンドの漏れ

### ISSUE THREAD

**Issue by ringkeng** [momijiame/linux-tcpip-book#1]
本書を楽しく読んで、実行しております。
1点テキストを見ていて、コマンドの漏れがあったので記載します。

■本文　3.2　veth指定時の「-」の漏れ
$ sudo ip netns exec ns1 ip address add 192.0.2.1/24 dev ns1 veth0
Error: either "local" is duplicate, or "veth0" is a garbage.

■正　（github上のコマンドも正しいです）
$ sudo ip netns exec ns1 ip address add 192.0.2.1/24 dev ns1-veth0

**Comment by momijiame** [comment]
本書を読んでいただきましてありがとうございます。また、問題箇所をご報告いただきました点について、重ねてお礼申し上げます。

ご報告いただきました点について、こちらでも確認してみました。ただ、本のマスターデータについては同様の誤りがあることを確認できませんでした。また、手元の端末でも同事象を再現することができておりません。たとえば、以下は手元の Kindle (macOS) で同箇所を確認した内容です。

<img width="815" alt="issue-1-book-3-2-ns1-veth0" src="https://user-images.githubusercontent.com/1781355/99918689-03449700-2d5c-11eb-9c6c-fad236718ad0.png">

一つ、考えられる可能性としては Kindle の不具合が挙げられます。というのも、他書ですが、似たような問題の報告を受けたことがあるためです。問題のあった箇所はソースコードを掲載した部分でしたが、同様に特定のユーザで表示内容の欠損がありました。その際は端末依存性があったため、別のプラットフォームの Kindle で確認いただいたところ、問題ないことが分かっています。今回の事象も、もし Kindle の問題だとすると著者側での原因追求は正直なところ難しい状況です…。大変心苦しく、申し訳ないのですが Amazon のサポートに事象の詳細をご連絡いただけますと何か手がかりが得られるかもしれません。(先述の事象について、サポートにこちらから問い合わせた際には、著者ではなく問題のあった読者側から問い合わせてください、という案内がありました)

一点補足させていただきますと、こちらの GitHub リポジトリの内容は、本のマスターデータから機械的に抽出しています。そのため、もし Kindle でコマンドラインやソースコードにおかしい点がありました際には、こちらの内容を正と考えていただくことができるかと存じます。

**Comment by ringkeng** [comment]
返信、ご確認ありがとうございます。
再度確認すると、fire HD10の縦向きにした際に「-」が見えず、横向きにすると表示されました。
せっかくなのでamazonに聞いてみようと思います。簡単ですが、以上です。
