### ISSUE TITLE
pyファイルの仮想空間での保存方法

### ISSUE THREAD

**Issue by Avrora4578** [momijiame/linux-tcpip-book#2]
ご執筆された書籍を購入させていただいたプログラミングの初心者です。複雑な内容でも分かりやすく書かれており、とても勉強になります。ありがとうございます。
今読み進めている中で詰まってしまったのですが、kindle版で77%の位置（No. 3334/4371）にあるhttpclient.pyファイルの保存につきまして、保存場所はvagrant upの状態で作成した/var/tnp/http-homeで宜しいでしょうか？また、VScodeで作成したpyファイルを仮想空間上の当該ディレクトリに保存する方法についてご教示いただけますと幸甚です。初心者のため的外れなご質問でしたら申し訳ございません。

**Comment by momijiame** [comment]
こんにちは。

> ご執筆された書籍を購入させていただいたプログラミングの初心者です。複雑な内容でも分かりやすく書かれており、とても勉強になります。ありがとうございます。

拙著をお読みいただきましてありがとうございます。そう仰っていただけると励みになります。

> 今読み進めている中で詰まってしまったのですが、kindle版で77%の位置（No. 3334/4371）にあるhttpclient.pyファイルの保存につきまして、保存場所はvagrant upの状態で作成した/var/tnp/http-homeで宜しいでしょうか？

Python ファイルを保存する場所は ``vagrant ssh`` でログインした仮想マシンの中であれば何処でも大丈夫です。
※ 付録の内容にもとづいて Vagrant + VirtualBox で環境をお作りになられている場合です

> また、VScodeで作成したpyファイルを仮想空間上の当該ディレクトリに保存する方法についてご教示いただけますと幸甚です。初心者のため的外れなご質問でしたら申し訳ございません。

VScode を動かしているのは、仮想マシンを動作させている物理マシン側という認識で合っているでしょうか？
その仮定でお話しますと、いくつかやり方があります。ここでは、その中でもやりやすいものを 2 つご紹介します。
※ これは、本質的には物理マシンと仮想マシンの間でファイルをどのように共有するか、という問題です

### 1) 共有ディレクトリを使ってファイルをやり取りする

このやり方は Vagrant / VirtualBox に備わっている共有ディレクトリを経由してファイルをやり取りする方法です。

物理マシン側の ``Vagrantfile`` があるディレクトリは、仮想マシン側で ``/vagrant`` というパスで共有されています。
そのため、物理マシン側でそのディレクトリにファイルを置いた上で、仮想マシン側で ``/vagrant`` に移動すればファイルにアクセスできます。

なお、この機能は仮想マシンに VirtualBox の Guest Additions が導入されていることが前提となっていることにご注意ください。
付録にある ``vagrant-vbguest`` プラグインを導入すると、Guest Additions が自動でインストールされるためおすすめです。

### 2) SCP コマンドを使って転送する

このやり方は Vagrant で仮想マシンにログインする際に使われる SSH というプロトコルでファイルを転送するやり方です。

以下の手順は、物理マシン側に OpenSSH がインストールされていて ``scp`` コマンドが使える前提となっています。

はじめに、``Vagrantfile`` のあるディレクトリに移動して以下のコマンドを実行します。
これで仮想マシンにログインするための設定情報が ``ssh-config`` というファイルで出力されます。

```
$ vagrant ssh-config >> ssh-config
```

その上で、以下のコマンドを実行してファイルを仮想マシンに転送します。

```
$ scp -F ssh-config httpclient.py vagrant@default:~/
```

※ ``httpclient.py`` は ``Vagrantfile`` のあるディレクトリに作成してください

上記で、仮想マシン側のホームディレクトリ (``~/``) にファイルが送られます。

**Comment by Avrora4578** [comment]
ご記載頂いた2つの方法どちらも上手くいきました。ありがとうございます。
またご執筆される機会がありましたら是非拝読させていただきます。

**Comment by momijiame** [comment]
上手くいったようで安心しました。
また何か不明点がありましたらお気軽におたずねください。
